### ISSUE TITLE
Use License

### ISSUE THREAD

**Issue by ritiek** [bjarneh/kotkit#1]
Hi @bjarneh. Thanks for your amazing work.

I want to put up your work on [kotlin.nanorc](https://github.com/bjarneh/kotkit/blob/master/misc/syntax/nano/kotlin.nanorc) on https://github.com/scopatz/nanorc so people can easily find and install it. But I cannot do so until you provide this repository a license. Do you mind putting up an appropriate license so that people can re-use your work legally?

Thanks again.

**Comment by bjarneh** [comment]
Hi,
sure. I haven't looked at this stuff in a while, so it probably needs some updates to work properly. Unless you have any preferences I'll just add a BSD compatible license; which I guess is the most permissive/flexible.

Best regards
bjarneh

**Comment by ritiek** [comment]
@bjarneh Thank you! :smile:
